// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp5s4OKUYUxEQ84Ek05WoQ7_RD48-3N40',
    appId: '1:543570116947:web:afa839fe7768b492c7e1a6',
    messagingSenderId: '543570116947',
    projectId: 'sceneo-17cf8',
    authDomain: 'sceneo-17cf8.firebaseapp.com',
    storageBucket: 'sceneo-17cf8.firebasestorage.app',
    measurementId: 'G-TK0XNWFMW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodZxlOcutCP86n6XLlIGSnCuwyJ1qB-g',
    appId: '1:543570116947:android:5b422666dc144890c7e1a6',
    messagingSenderId: '543570116947',
    projectId: 'sceneo-17cf8',
    storageBucket: 'sceneo-17cf8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmemkL-LYabDPCehSFE89a-8f9cbylSQo',
    appId: '1:543570116947:ios:11cb21048b25cc4ec7e1a6',
    messagingSenderId: '543570116947',
    projectId: 'sceneo-17cf8',
    storageBucket: 'sceneo-17cf8.firebasestorage.app',
    iosBundleId: 'com.sceneo.sceneo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmemkL-LYabDPCehSFE89a-8f9cbylSQo',
    appId: '1:543570116947:ios:11cb21048b25cc4ec7e1a6',
    messagingSenderId: '543570116947',
    projectId: 'sceneo-17cf8',
    storageBucket: 'sceneo-17cf8.firebasestorage.app',
    iosBundleId: 'com.sceneo.sceneo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp5s4OKUYUxEQ84Ek05WoQ7_RD48-3N40',
    appId: '1:543570116947:web:22225ddc04cc0a2fc7e1a6',
    messagingSenderId: '543570116947',
    projectId: 'sceneo-17cf8',
    authDomain: 'sceneo-17cf8.firebaseapp.com',
    storageBucket: 'sceneo-17cf8.firebasestorage.app',
    measurementId: 'G-R5MQ5CN3E0',
  );
}
